name: Magic Ticket
description: "Congratulate a user when they get the magic issue/PR/discussion number"
inputs:
  token:
    description: "The GitHub token to use"
    required: true
    default: ${{ github.token }}
  regex:
    description: "The regex to use to find the magic number"
    required: true
  message:
    description: "The message to post when the magic number is found"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
